import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

//import my components
import Header from "@/components/Header/Header";
import Nav from "@/components/Nav/Nav";
import Article from "@/components/Article/Article";
import Carousel from "@/components/Carousel/Carousel";
import { CarouselData } from "@/components/Carousel/CarouselData";
import ArticleList from "@/components/CardList/CardList";
import { articleList } from "@/components/CardList/articles";
import { flipCards } from "@/components/FlipCardGrid/flipCards";
import FlipCardsGrid from "@/components/FlipCardGrid/FlipCardGrid";
import PageContainer from "@/components/PageContainer/PageContainer";

const images = [
  "https://via.placeholder.com/800x400/ff0000/ffffff?text=Slide+1",
  "https://via.placeholder.com/800x400/00ff00/ffffff?text=Slide+2",
  "https://via.placeholder.com/800x400/0000ff/ffffff?text=Slide+3",
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header headerText={"Home"} />
      <Nav />
      <PageContainer>
      <Carousel slides={CarouselData} />
      <Article />
      <FlipCardsGrid flipCards={flipCards} />
      <ArticleList articles={articleList} />
      </PageContainer>
    </>
  );
}
